### ISSUE TITLE
TypeError: Cannot read property 'classList' of undefined

### ISSUE THREAD

**Issue by tylerrrkd** [gaoryrt/number-flip#11] opened 2018-10-26 10:45 UTC
It seems something wrong when I put it the following code in a `setInterval` function.
Code like following: 

```
      this.counter.timer && clearInterval(this.counter.timer)
      this.counter.timer = setInterval(() => {
        let newTime = new Date();
        this.counter.timeLeft = Math.floor((new Date(this.counter.startTime).getTime() - newTime.getTime()) / 1000);
        if (this.counter.timeLeft >= 0) {
          let h = Math.floor(this.counter.timeLeft / 60 / 60);
          this.counter.H = h < 10 ? "0" + h : h;

          let m = Math.floor((this.counter.timeLeft / 60) % 60);
          this.counter.M = m < 10 ? "0" + m : m;

          let s = this.counter.timeLeft % 60;
          this.counter.S = s < 10 ? "0" + s : s;
        } else {
          this.counter.timer && clearInterval(this.counter.timer)
          // 切换倒计时
          this.counter.GFlip = new Flip({ node: this.$refs.gifts,  from: 132486, duration: 2 })
          this.counter.GFlip.flipTo({ to: 131909 })
        }
      }, 1000);
```

**Comment by gaoryrt** [comment] 2018-10-27 04:03
@tylerrrkd any minimal reproducible example like, in codepen?

**Comment by tylerrrkd** [comment] 2018-10-27 10:40
@gaoryrt wait a minute, friend

**Comment by tylerrrkd** [comment] 2018-10-29 01:56
@gaoryrt Hi, friend, here is the codepen url https://codepen.io/Tylerrrkd/pen/NOJQdR

**Comment by gaoryrt** [comment] 2018-10-29 02:48
@tylerrrkd review your code plz
line 57 of js, `this.counter.timeLeft` would be negative
line 16 of scss, `width: .59rem;` would make the second number invisible
fixed in https://codepen.io/gaoryrt/pen/BqEBjd

**Closed by gaoryrt** 2018-10-29 02:48 UTC

**Comment by gaoryrt** [comment] 2018-10-29 02:55
`Cannot read property 'classList' of undefined` might caused by incorrect usage of vue

**Comment by tylerrrkd** [comment] 2018-10-29 03:51
@gaoryrt yep, I solved it after wrapped in a setTimeout statement, it may be caused by DOM's render speed.
